name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Show Node.js version
        run: node -v  # Verifica que se usa la versión correcta

      - name: Install dependencies
        run: npm ci  # O usa "npm install" si no tienes package-lock.json

      - name: Run tests
        run: npx jest --ci --verbose  # Activa el modo CI para evitar errores en entornos de GitHub Actions
